site_name: GLocalFlexTrade
repo_url: https://github.com/glocalflex/GLocalFlexTrade
site_url: https://glocalflex.github.io/GLocalFlexTrade
site_description: Energy trading client for the flexible energy platform GLocalFlex
site_author: GLocalFlex
edit_uri: edit/main/docs/
repo_name: glocalflex/GLocalFlexTrade
copyright: Maintained by <a href="https://glocalflex.com">GLocalFlex</a>.

nav:
  - Home: index.md
  - Diagrams: mermaid.md

plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/glocalflex/GLocalFlexTrade
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/GLocalFlexTrade

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
