name: workflow

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: pytest_cov_report
    steps:
    - uses: actions/checkout@v1
    - name: Install poetry
      run: pip install poetry
    - name: Install requirements
      run: poetry install
    - name: Run tests and collect coverage
      run: poetry run pytest --cov . --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
